name: Check ImGui Submodule

on:
  push:
  pull_request:

jobs:
  check_submodule:
    runs-on: ubuntu-latest  # Мы используем Ubuntu, но можно и Windows, если нужно

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Display current directory
      run: pwd
    
    - name: List all files in the repository
      run: ls -R
    
    - name: Check ImGui files
      run: |
        echo "Checking for ImGui files:"
        if [ -d "external/imgui" ]; then
          ls -R external/imgui
        else
          echo "Directory 'external/imgui' does not exist."
        fi
    
    - name: Check for specific files
      run: |
        echo "Checking for specific ImGui files:"
        if [ -f "external/imgui/imgui.h" ]; then
          echo "imgui.h exists."
        else
          echo "imgui.h does not exist."
        fi
        if [ -f "external/imgui/backends/imgui_impl_opengl3.cpp" ]; then
          echo "imgui_impl_opengl3.cpp exists."
        else
          echo "imgui_impl_opengl3.cpp does not exist."
        fi
        # Добавьте здесь проверки на другие ключевые файлы, если необходимо